# Generated by Django 4.2 on 2023-04-24 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Наименование организации')),
            ],
        ),
        migrations.CreateModel(
            name='Essence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(verbose_name='Внешний ID')),
                ('fact_qliq_data1', models.IntegerField(verbose_name='Фактический qliq_data1')),
                ('fact_qliq_data2', models.IntegerField(verbose_name='Фактический qliq_data2')),
                ('fact_qoil_data1', models.IntegerField(verbose_name='Фактический qoil_data1')),
                ('fact_qoil_data2', models.IntegerField(verbose_name='Фактический qoil_data2')),
                ('forecast_qliq_data1', models.IntegerField(verbose_name='Планируемый qliq_data1')),
                ('forecast_qliq_data2', models.IntegerField(verbose_name='Планируемый qliq_data2')),
                ('forecast_qoil_data1', models.IntegerField(verbose_name='Планируемый qoil_data1')),
                ('forecast_qoil_data2', models.IntegerField(verbose_name='Планируемый qoil_data2')),
                ('date_at', models.DateField(verbose_name='Дата')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.organization')),
            ],
        ),
    ]
