# Generated by Django 4.2 on 2023-04-24 06:52

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def create_base_organizations(apps: migrations.state.StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Organization = apps.get_model("db", "Organization")
    Organization.objects.bulk_create([
        Organization(name="company1"),
        Organization(name="company2"),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(code=create_base_organizations, reverse_code=migrations.RunPython.noop)
    ]
